### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by matthieupetel** [EmakinaFR/docker-proximis#9]
The "Proximis Omnichannel" link in the project description is dead.
Here is a valid link : https://www.proximis.com/solution/
:)

**Comment by ker0x** [comment]
Fix in #12

**Comment by matthieupetel** [comment]
Thanks man, you're awesome ! Let me tell you something : I really appreciate what you did ! Great work !

**Comment by ajardin** [comment]
@matthieupetel : lol sorry, I didn't receive the notification... 😕
